"""Output formatting and persistence."""
from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from paper_daily.database import PaperDatabase

LOG = logging.getLogger("paper_daily.output")


def format_markdown(papers: list[dict], date_str: str | None = None) -> str:
    if date_str is None:
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# 📚 Paper Daily Top {len(papers)} | {date_str}",
        "",
        "| # | 论文 | 学术分 | 推荐理由 | 链接 |",
        "|---|------|--------|----------|------|",
    ]

    for i, p in enumerate(papers, 1):
        title = p.get("title", "Untitled").replace("|", "\\|")
        year = p.get("year", "?")
        venue = (p.get("venue") or p.get("source", "")).replace("|", "\\|")
        reason = (p.get("reason_zh") or "").replace("|", "\\|")
        aca_score = p.get("academic_score")
        aca_reason = (p.get("academic_reason") or "")
        # Strip any residual XML-like tags (e.g. <reason>, </reason>)
        aca_reason = re.sub(r"</?[^>]+>", "", aca_reason).strip()
        aca_reason = aca_reason.replace("|", "\\|")
        url = p.get("url", "")
        if not url and p.get("doi"):
            url = f"https://doi.org/{p['doi']}"
        if not url and p.get("arxiv_id"):
            url = f"https://arxiv.org/abs/{p['arxiv_id']}"
        if not url:
            url = "#"

        score_str = ""
        if aca_score is not None:
            score_display = round(aca_score * 10, 1)
            score_str = f"**{score_display}/10**"
            if aca_reason:
                score_str += f"<br><small>{aca_reason[:60]}{'...' if len(aca_reason) > 60 else ''}</small>"

        lines.append(f"| {i} | **{title}** ({year}) <br> {venue} | {score_str} | {reason} | [链接]({url}) |")

    lines.extend([
        "",
        "---",
        f"*Generated by Paper Daily at {datetime.now(timezone.utc).isoformat()}*",
    ])
    return "\n".join(lines)


def format_console(papers: list[dict], date_str: str | None = None) -> str:
    if date_str is None:
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [f"📚 Paper Daily Top {len(papers)} | {date_str}", ""]
    for i, p in enumerate(papers, 1):
        title = p.get("title", "Untitled")
        year = p.get("year", "?")
        venue = p.get("venue") or p.get("source", "")
        reason = p.get("reason_zh", "")
        aca_score = p.get("academic_score")
        aca_reason = (p.get("academic_reason") or "")
        aca_reason = re.sub(r"</?[^>]+>", "", aca_reason).strip()
        url = p.get("url", "")
        if not url and p.get("doi"):
            url = f"https://doi.org/{p['doi']}"
        if not url and p.get("arxiv_id"):
            url = f"https://arxiv.org/abs/{p['arxiv_id']}"

        lines.append(f"{i}. 【{title}】({year}) {venue}")
        if aca_score is not None:
            score_display = round(aca_score * 10, 1)
            lines.append(f"   🎓 学术价值: {score_display}/10 | {aca_reason}")
        lines.append(f"   💡 {reason}")
        if url:
            lines.append(f"   🔗 {url}")
        lines.append("")
    return "\n".join(lines)


def save_outputs(
    papers: list[dict],
    db: PaperDatabase,
    data_dir: Path,
) -> None:
    """Persist to DB and write markdown/json files."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    for rank, p in enumerate(papers, 1):
        # Insert or get paper
        paper_id = db.insert_paper(p)
        db.insert_recommendation(
            paper_id=paper_id,
            rank=rank,
            score=p.get("_scores", {}).get("total", 0.0),
            reason_zh=p.get("reason_zh", ""),
            academic_score=p.get("academic_score"),
        )

    # Write files
    md = format_markdown(papers, today)
    md_path = data_dir / f"recommendations_{today}.md"
    md_path.write_text(md, encoding="utf-8")

    json_path = data_dir / f"recommendations_{today}.json"
    json_path.write_text(
        json.dumps(papers, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    # Also write latest symlink-like file
    latest_md = data_dir / "recommendations_latest.md"
    latest_md.write_text(md, encoding="utf-8")
    latest_json = data_dir / "recommendations_latest.json"
    latest_json.write_text(
        json.dumps(papers, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    LOG.info("Saved to %s, %s, and latest.*", md_path, json_path)
